### ISSUE TITLE
Cool idea, how have your results been?

### ISSUE THREAD

**Issue by samedii** [pbaylies/Augmented_CLIP#1]
Sorry for posting an issue for this but was really curious about what the results are like :)

_I tried out your version to compare against a non-augmented embedding without diffusion/vqgan to see the "raw" results but I find it's not directly obvious with these things to see what works "better"_

**Comment by pbaylies** [comment]
@samedii it varies, but the images on the repo and a lot of the images I post on Twitter are representative of what can be generated with these models in the mix. It'd be nice to have some real benchmarks / tests or image studies to point to, for sure. Ideas welcome, I'd like to see that for lots of models, not just mine. :)

**Comment by samedii** [comment]
Thanks! :D

**Comment by samedii** [comment]
Did some tests with a more "raw" drawer than diffusion and thought maybe you would be interested. Only using `aug_clip_models = ["_avg1"]`

Text prompt was `warrior. concept art. trending on artstation` and starting from fractal noise.

1. without embedding augmentations
2. only added `text_to_image(txt)`
3. also added `image_to_text(text_to_image(txt))`
4. code in repo with `model_depth = 100, model_avg_freq = 10`
![image](https://user-images.githubusercontent.com/1872050/161432177-3beb8985-15e6-47ec-8b06-6a2cc6278176.png)
![image](https://user-images.githubusercontent.com/1872050/161432209-c24c9149-f221-4e64-bb38-28d351769ba2.png)
![image](https://user-images.githubusercontent.com/1872050/161432251-8324aca2-6269-49b6-8627-affb317404ba.png)
![image](https://user-images.githubusercontent.com/1872050/161432323-e0407a7e-874f-43a8-bb2e-af0b71078f4b.png)

Not completely clear but looks pretty convincing at this point.
